<?php
/* @var $this ConfigController */
/* @var $model Config */

$this->breadcrumbs=array(
	'Configs'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Config', 'url'=>array('index')),
	array('label'=>'Create Config', 'url'=>array('create')),
	array('label'=>'Update Config', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Config', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Config', 'url'=>array('admin')),
);
?>

<h1>View Config #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'board_works',
		'add_new_ads',
		'add_new_news',
		'id',
		'cache_clear',
		'scache',
		'scache_expire',
		'scache_exp_expire',
		'kcache',
		'add_new_only_user',
		'money_service',
		'top_status_days',
		'top_prefix',
		'top_price',
		'top_number',
		'select_status_days',
		'select_prefix',
		'select_price',
		'select_number',
		'wm_money_service',
		'wm_mode',
		'wm_purse',
		'wm_type',
		'wmprice_vip',
		'wmprice_select',
		'subscribe_theme',
		'subscribe_text',
		'subscribe_from',
		'subscribe_limit',
		'subscribe_sleep',
		'view_nonactiv_contacts',
		'count_symb_autor',
		'count_symb_title',
		'count_symb_url',
		'count_symb_contacts',
		'count_symb_text',
		'count_adv_on_index',
		'tags_generate',
		'kaleidoscope',
		'count_show_img_kaleidoscope',
		'add_url',
		'view_comments',
		'clouds_tags',
		'add_comments',
		'stop_words',
		'upl_image_size',
		'mail_friends',
		'admin_mail',
		'print_keywords',
		'print_vip',
		'count_print_vip',
		'print_news',
		'count_print_news',
		'count_news_in_page',
		'print_stat',
		'limit_pagination_on_page',
		'mail_about_new_mess',
		'upload_images',
		'count_images_for_users',
		'width_small_images',
		'width_normal_images',
		'width_cat_images',
		'width_news_images',
		'add_link_to_video',
		'captcha',
		'edit_message',
		'edit_comments',
		'anti_link',
		'day_for_notice_autor',
		'user_title',
		'user_keywords',
		'user_description',
	),
)); ?>
